FROM python:3.8.5-slim-buster

# jupyter
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt update && apt install -y nodejs npm
RUN pip install jupyterlab 
RUN pip install jupyter-lsp python-language-server[all] 
RUN jupyter labextension install \
    @lckr/jupyterlab_variableinspector \
    @krassowski/jupyterlab-lsp
RUN jupyter lab build

RUN pip install boto3 elasticsearch==7.8.1

RUN mkdir /notebook
WORKDIR /notebook
# library
CMD jupyter lab --allow-root --ip 0.0.0.0 --NotebookApp.token=''